// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/protobuf/worker_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace grpc {

namespace protobuf_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto {


namespace {


}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tensorflow/core/protobuf/worker_service.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::tensorflow::protobuf_tensorflow_2fcore_2fprotobuf_2fworker_2eproto::InitDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n-tensorflow/core/protobuf/worker_servic"
      "e.proto\022\017tensorflow.grpc\032%tensorflow/cor"
      "e/protobuf/worker.proto2\231\007\n\rWorkerServic"
      "e\022H\n\tGetStatus\022\034.tensorflow.GetStatusReq"
      "uest\032\035.tensorflow.GetStatusResponse\022f\n\023C"
      "reateWorkerSession\022&.tensorflow.CreateWo"
      "rkerSessionRequest\032\'.tensorflow.CreateWo"
      "rkerSessionResponse\022f\n\023DeleteWorkerSessi"
      "on\022&.tensorflow.DeleteWorkerSessionReque"
      "st\032\'.tensorflow.DeleteWorkerSessionRespo"
      "nse\022T\n\rRegisterGraph\022 .tensorflow.Regist"
      "erGraphRequest\032!.tensorflow.RegisterGrap"
      "hResponse\022Z\n\017DeregisterGraph\022\".tensorflo"
      "w.DeregisterGraphRequest\032#.tensorflow.De"
      "registerGraphResponse\022E\n\010RunGraph\022\033.tens"
      "orflow.RunGraphRequest\032\034.tensorflow.RunG"
      "raphResponse\022Q\n\014CleanupGraph\022\037.tensorflo"
      "w.CleanupGraphRequest\032 .tensorflow.Clean"
      "upGraphResponse\022K\n\nCleanupAll\022\035.tensorfl"
      "ow.CleanupAllRequest\032\036.tensorflow.Cleanu"
      "pAllResponse\022M\n\nRecvTensor\022\035.tensorflow."
      "RecvTensorRequest\032\036.tensorflow.RecvTenso"
      "rResponse\"\000\022B\n\007Logging\022\032.tensorflow.Logg"
      "ingRequest\032\033.tensorflow.LoggingResponse\022"
      "B\n\007Tracing\022\032.tensorflow.TracingRequest\032\033"
      ".tensorflow.TracingResponseB3\n\032org.tenso"
      "rflow.distruntimeB\023WorkerServiceProtosP\001"
      "b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1088);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/protobuf/worker_service.proto", &protobuf_RegisterTypes);
  ::tensorflow::protobuf_tensorflow_2fcore_2fprotobuf_2fworker_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_tensorflow_2fcore_2fprotobuf_2fworker_5fservice_2eproto


// @@protoc_insertion_point(namespace_scope)

}  // namespace grpc
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
